language: go
go:
- 1.11.x
branches:
  only:
  - master
install:
- ./install-hugo-from-gh.sh
- sudo pip install awscli
script:
- hugo --cleanDestinationDir
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website-external
  local_dir: public
  skip_cleanup: true
  region: us-west-2
  on:
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: Ei1eqAQ2msQh7zaFow9sJBnilL8ta1jOdwRt9MAr4/YqRU++HqvFuZbANSxI12H5EnJRjUseyZn4+xvt/LB1e6Be6sWKoGr+td8WcbXWSubj46jvPUaADJHrXHswEXpLIeh9Dk8BfePZiWbaN8ImicZxxJoknMnc/MbqT8spyu81Ep1wDT+IRXIuUdyFpjpRdh5/sc1isruCdcUwsUAPsNVIVi2XKfHUfczHl7ECJ0fu/WP3AhL0qjOp5E3t94NxeAbzvDX6XXdT5wWvZOEKUNx1niIf4skLSrYR3F5e7/bX1ura0NX7AqwgHNgt6/y+JCsaQFzwN8BlwdVL4jAFWzmWeeHLrmph+OObMem8ry19bp5bQ5078NRUTJvS6n6cUwYbMZ2RxPRWRCrxwc9DUUAyMgqhGzgLxnjfm3j8xVY4VV0RuP6Ff5mZzh/gmnXVN0+Kf/C1aalLqvl0ZPqI1huWkdBDyfETmzpgjDm/2IXFak4sf7Ifz30OFJC8uiK79rtb8P0vti7qGuKxFr44mHQlLMY0X8tMWDdHeN8QeXavuHjGL6RZzGjUJyL+Yhj8DXivDTOWvNBgImP2ZJ23aAqsvBWZ8iy1dA1w2F+0cyqWR8ymyZarhhbQ5huOpkoDOfcITKOe+mSicB5DpLrXdRFSWn+R5GIJQRxuTGHTDMY=
  - secure: oGC5Jk2CDFEPN0H/ToDFr+Tja/ODF3gZ9VfmhKXSeQ2tYt4aaLWGp4AXfTxnRIxcB3ovC+qk0gMCekK+wGq09DkvTex+MxxUxSuUVyFWOyIqT/kGSgayEfKp15vAPlzUDw0VuaQWn3MzSogrC6vWm4zu6UFOse4XXn/mYjvCOVp+8/nWvimOtly2XDFdgoOXBGjQR/3PqGlDBgHnmJoIkCQZW7xK+rybWPKwTZ7fcVPaC0NG3c1e2hpnn8qiMvsgBe31WGA7i0RKWa+w5gLXi2G1dIfyztYoCV898t16lXoMUbzyzd+tCa3oxHLsxKFmNNdXA+HQ5VAJPrEPOFIBEkC56pZKiRdCEi2C7VhXUuD5PrOe75fptcJM2LS9vQctAAKE9/1FI1O3EuYS1AqrBo5kKMqpHDFJO640unfr1VcTrmBpRbnQTiLIRMBPeJpy5VA4fyGG9NXeWPGCvO11CEziLDVBh00EeEMNJiFkhMHN6clD3ezRIsDfqAR/z9qZRpLyFa12+KrBN0EobN3PqWXQoP1zfBXQu/cPOYjhE1z3MCDN2oRS5smCQrrJ2+l2eg5kguz6NKRHiATZ4O4kyDrI/wvrX8aHD48MCRk6inFbyREycEy7K6+M/n3dm2w/q7GXQxVDRy5te3jaWT/iGhz15OnxlrFjfyrSq8Vz52Q=
  - secure: ur1LXR/h+36AmnpDlmGlfH9D1lv6MytAVbFKkVtiLvD+KAbszVuXj+/hOrMl+qmPhf++8npkaZ764pLk5vFlS+fetyiKgwNzVEZvnD0+GBBC2ZOL/t8GVYaPuc3D+FLYNszz4mM+rgYty0fsBj8F+jkdW4bAKca6PzQqlG2Pc9WED9JH4KEqyRjneZuo6aetHDDO1B05CZ4crYM7SBoiFNRV37EBRoHeYNHp5oVqecEcfAgdyZLE8QVJ7rmLZU04x8I3i0YM1aVVdPLOh1SA40EbcmvLWb1PaGFOshusbvFFHSb6mTBfjrlo6o7On9AH8NDe/HZibf7P/wel3dKo9fiqgyLFeGUKsOYMfxtoZye9d6rmz6UmEsZA8Z3dbquqTc45TD+0JI193v8mkiubdYQv1ZK6Lj4fTC7AdoaNbvtycojOvInmxxGx464wLtpGaLY/vAX3R4j9yvzq2wOPfQ1YOwZhn3XkOxtZwY2TIGSA9ARDxvnBaWt5VvryvFiEpivpdzJ9a390M+OBm25Rcxu8QV16EFjScM3KucMb1ItQItYWWkCzgBLNMVyz2DNnuwv5xQFzxWRV0cXlqobSfkEGhBcIIOgDTXd6N8+rh3lcSbXhwhzk6/aONtrki11OMX94K92/cvMakZMuhFFT2RcOQ1au/hKonBwdocpbXbc=
  - secure: ok5cYVoND6y7eeE1wkvRZddXq+iT3HcVaNpE+JgVaasA0DNxHXIpsoa1NEjrfGXf2Tx7v4I4SKPAFBVnKEd35EargHO/DadD/aF5JRsEfSjM2ThXviF7sKlcIzgTmtj4KjI6EXQCLfFEJfVQK+KqeTmgvPCQWe9uZW1NHANaTuz+ECvHEA9V+0udRYUG/u/HDYzA2WNV2BL4q48SqAIV1lex7FbrAzseYkNBWv9xaxWdyElYknyO6ZodDSnSmJHlHQYLgPQzwzebm/18gWvoRD/OO1ECeHZXls0e9Uz8PfiSm0VQQNZVU5xMjhYL7mgjeW3jzGTZvK47ermMa2Ym947WC9J/rhCEb51qweAtqqSQLDID8tHKrM0NRy+1ufLGp6rqKPO7jY0INPPlVA0xxTHN3n4MjlTSyJSMUqRl1HqAiNYlMz4yCe+710Z4TkC0q/eykFhieTuJgYtxFBCc1N3Tja5rfY91QLA9OzboNfBLeIqblGj5Sh4FTwoRv9Ca668kC42GDmLEBAfUsLnbXE/MErJQzWnKYHnlJLk1+V1GjIMGoXd9h6yGs+R3BX0T72DcwcKjaXzoqLWJQcfm/9cvlz+Is892mAcTS/Pg+1TFCg/mYTcb/dB3niSEtT6F7Jt5eeGh/PYq5XLfKBQSPfAv4p9UtDn9pRPlUVWtoZM=
  - secure: 0p0rj7TDCXmY9Z/iHq3avMYExGgNNgUtv7yOgVeJ0VcdiHzyjotDEP2zzQwV0FqucVFr/sOqbFkv/hYiBQ4VIVIz3pAKVna1OM32akYbnetCuP+NFHb2hF04pCMu0X5efiZzGi56N6+m/uniGLw5g+dCl5+qasBaUuzrJHFisISD7pKydIZ5OlaFUxPD45lfYooPwULfy8tHlgEdaNzJ3zmzT5m3o7IFSNCxN+P0yOoHTFGmZyLuxpv9pFLxEYJrJae6ELa02w5fj7cGapf3ZpI2kEEk1dZkcQ9X9qtp68GSD1mD+jAA7jv2bRFkHQza+1CFsVsze2O54wWPvPprFi28C0O0NEToQc7MABZpSc2jVElVkBQc47iAcVNz6/qzDCdOaGHB9ewxNBMLnqBQHHsJRVh4xeMPnJAz1oCls0iXTipBUHfXPEdU0OGnbQhw+EvsBJ/Wk1msj49twIJhwTLaLk+GnI2AhWGJlIRoBwXvx+N/j+A+mCkhWQ3v0yzkJUphxv7DsQ69zqJwa1H+Q90+jlxGKo5TWA1QBZe6cp675O240Zq1JJ2RFleyee22mowdIgyClprumqThiiGk1l7Zv8gcSJvUSp1XkGJAxtdp7o0HIDLuUDC4LhkatqZPAB4NGMcauzd5+DOK3TtK+hibPmz0O369htvjtyyotBs=