language: go
go:
- 1.13.x
branches:
  only:
  - develop
install:
- ./install-hugo-from-gh.sh
- sudo pip install awscli
script:
- hugo --buildDrafts --cleanDestinationDir
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website
  local_dir: public
  skip_cleanup: true
  region: us-west-2
  on:
    branch: develop
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: peXk0xKLQkVBNPZlx5/q5l5/ZQXFzmsktagA10bBCUq2I/dsJnkZvggpSOsJlvI6+uws9ezpllwZoclXT2xqLLzstw/jFGQPkVFQcL9bavDV6wQh3sxx/NipvgrRSrH3dkjC8UmiXsrxkx9WXczenI57mZFTdXFyXWbODUghKGT5BIzIf00HSxTUC8CYXUuJVXi1V9XxS+X5INn7gQoi8btn9n94MG6AO3zgq34D+YSBaEh7iS4Z21BK7TGn243XdE3uABDuvm5JPWxcB3JtpmwEhOKd5cOFz++0u6Xiu4O2Tff3IhbKeNnyr2eCRlzBu+8hCP3sGjcdhf4FPNMaAr0K4LVe7uM/9gxH7LnuFpTx975FEAfvPLeNo1ArsBwLgSSssn+2Ongf7mC2Ul3iyVWE/3EpLM1NVWk/aczwmDva+OroM3VX4CaG9A1g2BPX8l820HW4uBrxso982h1Velet8EUjNwB0nM7pP/6+e0ku1vOQHvj8gyzEXaHvf9VOcahW6+dsfCIXBhekbmdu0KXZ9OwVZJ6o41A5oKBCqaF/+biV6i90ER0zow8625zfaaYYUz8Gt5piHwMEzOUTRvOuZQDfu+OpQkaih5qAJPyPhkzPzuh1M1ucF1hsUoKrNDHESkynQpKBz8W8Q411RHPN+yMJPslO84QITipNIU4=
  - secure: opg8ASBERTkjyO2qz2lIsB4Dn6qM1m9EF6+5aqsgdP7MZQnVRJtEFgUD5tDtlnkxcYSkVhI7InksAmA83EUbUjQB6q73qT/Rw5KwIrpxxQPyzbcuhX3SkFmkMsjz13La7CqIBL4Gy5wOlrOBkK62tHYEr/9t9Ap7ewG8Zi6rVb1339Rz3a3VjIjDy9V1wHW305T9opCk1tFq7mcHhXuXDPE6f5Xhid8EEN0vFW3r8gGggqOk7a4hHNLItbk+GmU8sNIBknaz587ZDhT5HLmpYmEdCyKMnnN6xv07K6ZsWNiMFunYnco1y4ZJWxsKm4HxbLEgAGOsw/7J+/p79Qb//tjWLbgYf4kAGf57urP7BflxRDhYa1XWdabFJPc3+MeClsQ/P0dSY0SNMTZeAehrQzecoVCQzak8pRqOp4LS0MKjEr25tv6bAIQBQZO5g4CLCQPFMdaGj75klnf726RFVHbXtJDAU+gW+YKOg8T6eRtYlH3BUg9zOSJNmhywrSlMFGH4N5vwRZ8X5S/TnGFXrKPA4QOVK3ztpA+lHgmhIKoY9ssz6fxeHDbus8nSi12MzW0IKWETcnOPPYWXZLRZvT4FvIshC5zSYDjh5CyhRmzVrcm5tuzBx5ub0AK7BCwsm+8fMFWG1sPFjE2ls7YLzH3qKPlCxMM6oM7/j+eJmF4=
  - secure: JJM4yrkD5fYMdU8ez5KBatT/x4zAWD4Rvz+jAaq4Oa6AURqpzsZ9hDPyk7M+ILvA0PYkKh1GMeA+42aDFOXI3+FxYRh2HdZgJW7ucW81+a1V6sOCR2JAyHiTTntyn2eIZvr0lQl+62qemYkb1jZqp+3l7wDlzYDB7iU6iW40QBhH5NjY7Azi6EOmgoJD2ftYtEwayvCxexXdKueLrqS43gRi+uX8/ArpEqXVDXrySZp8NeXtQjZuS+iSRJSGcL/OezMBIUOM3bfongwq01toVKtjJsXb1bsh6Sgg1ppUsQIAXT+GeVa1a+ZYUUJVE8Sp3PBXl4gUgSJS41EuU/cLzCkukRcSyNNFdwY10V+8QeQrbAHWvnJc5ulRQShGfkqBuc9s8PVYdeKt0OjAKo8UuV5TzMgTQMyIvbML442ynpWUlOFMEvDfBoc+aeJDCFlMB4WqtQwdjGdjxqY64de3lKwXviXk42QNcxKCs/4JO4QUOOxMKQ9ogE0L2XEPDR7ovl4EWOunxkAqA31CbrFhHtw8R5Q/2OFr0lcSG/xNR8cyUTIYui6RIhnJU2o6U1vX4g4/PvpKRgnhK35Etn04XbCsj+dGdF9p62rgpDP5TWjqtwziVoEruk58HsUYi7P3eH64gx+rggECWy28JKCEMTFE8HiD278BJF0hatU5IeM=
  - secure: jREclFBdPDyZ1+x11NBMyAewQqmR3MhgFzquPH5eB4Z6Q5tI0v6ptz/PA9D0BL3DQj2MNxdeqEzmAZbWjkP4ELgVCqDZdwHBGyxyfcbjuA3+9pFSkFv5+AIZrADq4kuOj82sDxzsARqP6kKFeKK7n3ac7ofxLQwnrfpakTyPGa8T09aUgy7D4maiwJnY+d+3IfFwoDMmyaOlyK1InipAMt8j5n9UhNjF23B/cNK8N0bhXCEZek9bZfnk0sXoyK6bBhOEcJ/pu/v9ySIVOpz5VB19dGwcqyZRc2GCDlPO5bSCh/xEhH5voXf6X9/8v1e06hpnzQnvtwS50j1NNlwhyIKYtKRiGz/oq5tYu7VMjrpKzwQxydCHbxzogwoaqBzMd5P8wTjqdI4/PUhqGmhJ8oIesYP7OYewZ1fiEhq+fe7AMfzX7XFWKF8i64R88SreG1waHd6LUcjzsRxpfcXriYMyf9QEPiCgHr17d85fOKSdCB5Cf52wzb1zEIp1TtSEpLtuBfmARJ2e4/1K/ORj+iI9lWEkakd+og3MfQAb2EQvAnheMP1zA7Xk+1GcIiaTiHhEZeGx3XrVDVVdVuOJn0t777mAdPHML1kn7S/w/qGb7ppI/pznkXGbz7EVDM0OR2wZkcCOQotIz4o38XPgAgybn6w4+HEVMWhPgMDvxy0=
  - secure: wIwE8ldn4jRIja4YU/wrFq3dEdyFQSkFgLYnqS6lL9gyp9KKwzg/sMkbOuoz1lda6FVA3Fq+2Um5zaV9MMZTSZQst/g9AU6LGGreEj2pf9GIz63sHMVKtaEDpbqvB7/CMtnp2IhWy9L60omgH+3RibZZ5o5WCZz/3EJxJXpkzqYQan+x4p94nJnmml6nIEd3HvZegOzgdZHcs58H503LywJ+hBzvq8+r5B/RwvLpr6y9wbTAonOhvuQToziUyW4p7JeYUKGaxqf9o+VA5pSHnsRuX5X0uv8OQ7u29cqtgstcwQf8evtPyN97meLcxahsQNVJzo2qMQDQK10v/aVv4HFvEsx88RikjYjAmKPWbgjncJCx8wr1v1tCRD0GMJ17ElED+KplFZOCdFTLlv76EP+Si649/CWAXZotMQJRhHi3jDC7XFr5ZFvouafppWIjXMYseMIaTOnFF/lggrKfESRQ6QejhHJ3xPyeSKcgh5ZFWhGZCreqOtNYcsCMregYmnrd9KioF0dULTtqr7Fb+gfB4xpeex7cjFHhxRfHX755JrIhwdQaxzfykVDvRwp23qcIDcPgoZWFJYZcRB87nGdUf+nHo33M9kfk7rWo5dpuYN0SW6SUIBdADTnxqLZMpKJoQsKz9qqVsbaf6YTHb+rhCQ5VyNTLYUZkaEo79vw=
